# Generated by Django 2.2.17 on 2021-02-06 21:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('anrede', models.CharField(blank=True, default='', max_length=50, verbose_name='Anrede')),
                ('titel', models.CharField(blank=True, default='', max_length=50, verbose_name='Titel')),
                ('vorname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=50, verbose_name='Nachname')),
                ('fahrtenname', models.CharField(blank=True, default='', max_length=50, verbose_name='Fahrtenname')),
                ('geburtstag', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('todestag', models.DateField(blank=True, null=True, verbose_name='Todestag')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-Mail')),
                ('stand', models.TextField(blank=True, choices=[('St.-Georgs-Ritter', 'St.-Georgs-Ritter'), ('Ordensritter', 'Ordensritter'), ('St.-Georgs-Knappe', 'St.-Georgs-Knappe'), ('Späher', 'Späher'), ('Knappe', 'Knappe'), ('Jungwolf', 'Jungwolf'), ('Wölfling', 'Wölfling'), ('Gildenmeisterin', 'Gildenmeisterin'), ('Pilgerin', 'Pilgerin'), ('Novizin', 'Novizin'), ('Gildin', 'Gildin'), ('Gildenmädchen', 'Gildenmädchen'), ('Jungpfadfinderin', 'Jungpfadfinderin')], null=True, verbose_name='Stand')),
                ('anmerkung', models.TextField(blank=True, default='', verbose_name='Anmerkung')),
                ('nicht_abdrucken', models.BooleanField(default=False, verbose_name='Nicht im Adressverzeichnis abdrucken?')),
                ('nrw', models.BooleanField(default=False, verbose_name='Kommt aus NRW?')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('nummer', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\d+$')], verbose_name='Nummer')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Bezeichner (Privat, ...)')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adressverzeichnis.Person')),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefonnummer',
                'verbose_name_plural': 'Telefonnummern',
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organ',
                'verbose_name_plural': 'Organe',
            },
        ),
        migrations.CreateModel(
            name='ManuelleBerechtigung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('bekommt_einladung', models.BooleanField(default=False, help_text='Zum überschreiben', verbose_name='Bekommt Einladung?')),
                ('bekommt_protokoll', models.BooleanField(default=False, verbose_name='Bekommt Protokoll?')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adressverzeichnis.Organ')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adressverzeichnis.Person')),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manuelle Berechtigung',
                'verbose_name_plural': 'Manuelle Berechtigungen',
            },
        ),
        migrations.CreateModel(
            name='GruppierungsTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gruppierungs Typ',
                'verbose_name_plural': 'Gruppierungs Typen',
            },
        ),
        migrations.CreateModel(
            name='Gruppierung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichner')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obergruppe', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adressverzeichnis.Gruppierung')),
                ('typ', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adressverzeichnis.GruppierungsTyp')),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gruppierung',
                'verbose_name_plural': 'Gruppierungen',
            },
        ),
        migrations.CreateModel(
            name='AmtTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amt Typ',
                'verbose_name_plural': 'Amt Typen',
            },
        ),
        migrations.CreateModel(
            name='Amt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('bestaetigt', models.BooleanField(default=True, verbose_name='Bestätigt?')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gruppierung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adressverzeichnis.Gruppierung')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adressverzeichnis.Person')),
                ('typ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adressverzeichnis.AmtTyp')),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amt',
                'verbose_name_plural': 'Ämter',
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('veraendert', models.DateTimeField(auto_now=True, verbose_name='Zuletzt verändert')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='Bezeichner (Privat, ...)')),
                ('strasse', models.CharField(blank=True, default='', max_length=100, verbose_name='Straßenname')),
                ('zusatz', models.CharField(blank=True, default='', max_length=50, verbose_name='Zusatz')),
                ('plz', models.CharField(blank=True, default='', max_length=15, verbose_name='PLZ')),
                ('stadt', models.CharField(blank=True, default='', max_length=100, verbose_name='Stadt')),
                ('land', models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Land')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adressverzeichnis.Person')),
                ('veraendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adressen',
            },
        ),
    ]
