# Generated by Django 2.2.17 on 2021-03-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adressverzeichnis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amt',
            options={'verbose_name': 'Amt oder Mitgliedschaften', 'verbose_name_plural': 'Ämter und Mitgliedschaften'},
        ),
        migrations.AddField(
            model_name='person',
            name='alte_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Alte ID'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='label',
            field=models.CharField(blank=True, default='', help_text='(Privat, ...)', max_length=50, verbose_name='Bezeichner (Privat, ...)'),
        ),
        migrations.AlterField(
            model_name='gruppierung',
            name='obergruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='untergruppen', to='adressverzeichnis.Gruppierung'),
        ),
        migrations.AlterField(
            model_name='gruppierung',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adressverzeichnis.GruppierungsTyp'),
        ),
    ]
