// Generated by CoffeeScript 1.8.0
(function() {
  var check_form_botcheck, check_form_input;

  check_form_input = function(id, title) {
    if ($(id).val() === "") {
      $(id + "-div").addClass("has-warning");
      return false;
    } else {
      $(id + "-div").removeClass("has-warning");
      $(id + "-div").tooltip().tooltip('hide');
      return true;
    }
  };

  check_form_botcheck = function(id, title, value) {
    if ($(id).val() !== value) {
      $(id + "-div").addClass("has-warning");
      $(id + "-div").tooltip({
        placement: 'bottom',
        trigger: 'manual',
        title: title
      }).tooltip('show');
      return false;
    } else {
      $(id + "-div").removeClass("has-warning");
      $(id + "-div").tooltip().tooltip('hide');
      return true;
    }
  };

  $(function() {
    return $("#submit").click(function() {
      var title, valid0, valid1, valid2, valid3, valid4, valid5;
      $('[data-toggle="tooltip"]').tooltip();
      title = "Bitte fülle dieses Feld aus";
      valid0 = check_form_input("#firstname", title);
      valid1 = check_form_input("#lastname", title);
      valid2 = check_form_input("#email", title);
      valid3 = check_form_input("#subject", title);
      valid4 = check_form_botcheck("#botcheck", "Bitte beantworte die Frage mit ja", "ja");
      valid5 = check_form_input("#message", title);
      if (valid0 && valid1 && valid2 && valid3 && valid4 && valid5) {
        $("#contact-form").hide();
        $("#proceeding").show();
        return $("#contact-form").submit();
      }
    });
  });

}).call(this);

//# sourceMappingURL=contact.js.map
