// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    console.log("Foo");
    return $("submit").click(function() {
      return console.log("Click");
    });
  });

}).call(this);

//# sourceMappingURL=contact.js.map
