# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-15 08:31
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('file', models.FileField(upload_to='maedchenbund', verbose_name='Datei')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
            },
        ),
    ]
