version: "3.7"

services:
  web:
    image: ghcr.io/deutscher-pfadfinderbund/dpb:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - web_static:/app/static
      - ./media/:/app/media
    env_file:
      - production.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      start_period: 30s
      start_interval: 1s
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./db/data_13:/var/lib/postgresql/data
    env_file:
      - production.env

  proxy:
    image: nginx:1-alpine
    restart: unless-stopped
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dpb-main.rule=Host(`deutscher-pfadfinderbund.de`) || Host(`www.deutscher-pfadfinderbund.de`)"
      - "traefik.http.routers.dpb-main.middlewares=redirect-www-to-non-www@file"
      - "traefik.http.routers.dpb-main.entrypoints=websecure"
    networks:
      - default
      - web
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
      - web_static:/usr/share/nginx/html/static/:ro
      - ./media/:/usr/share/nginx/html/media/:ro

networks:
  web:
    external: true

volumes:
  web_static: