version: "3.7"

services:
  web:
    image: cmeter/dpb
    volumes:
      - ./static/:/code/static
      - ./media/:/code/media
    env_file:
      - production.env
    networks:
      - dpb

  db:
    image: postgres:11-alpine
    volumes:
      - ./db/entrypoint:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - production.env
    networks:
      - dpb

  proxy:
    image: nginx:1-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:deutscher-pfadfinderbund.de,www.deutscher-pfadfinderbund.de,jungenbund.de,www.jungenbund.de,maedchenbund.de,www.maedchenbund.de"
      - "traefik.frontend.redirect.regex=^https?://www.deutscher-pfadfinderbund.de/(.*)"
      - "traefik.frontend.redirect.replacement=https://deutscher-pfadfinderbund.de/$${1}"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - dpb
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
      - ./static/:/usr/share/nginx/html/static/:ro
      - ./media/:/usr/share/nginx/html/media/:ro
    depends_on:
      - web

networks:
  web:
    external: true
  dpb:
    driver: bridge