version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - production.env

  db:
    image: postgres:10-alpine
    volumes:
      - ./db/entrypoint:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - production.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_ROOT_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
