version: "3.7"

services:
  web:
    image: ghcr.io/deutscher-pfadfinderbund/dpb:latest
    restart: unless-stopped
    volumes:
      - ./static/:/code/static
      - ./media/:/code/media
    env_file:
      - production.env
    labels:
      - "traefik.enable=false"
    networks:
      - dpb

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - ./db/entrypoint:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - production.env
    labels:
      - "traefik.enable=false"
    networks:
      - dpb

  proxy:
    image: nginx:1-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dpb-main.rule=Host(`deutscher-pfadfinderbund.de`) || Host(`www.deutscher-pfadfinderbund.de`)"
      - "traefik.http.routers.dpb-main.middlewares=redirect-www-to-non-www@file"
      - "traefik.http.routers.dpb-main.entrypoints=websecure"
    networks:
      - web
      - dpb
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
      - ./static/:/usr/share/nginx/html/static/:ro
      - ./media/:/usr/share/nginx/html/media/:ro
    depends_on:
      - web

networks:
  web:
    external: true
  dpb:
    driver: bridge
