# Generated by Django 3.2.12 on 2022-03-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrtenname', models.CharField(max_length=128, verbose_name='(Fahrten-)Name')),
                ('gilde', models.CharField(max_length=128, verbose_name='Name der Gilde / Horte')),
                ('bundesgruppe', models.CharField(max_length=256, verbose_name='Bundesgruppe')),
                ('gedanken', models.TextField(verbose_name='Wenn ich an den Bund denke, dann...')),
                ('sagen', models.TextField(verbose_name='Und was ich / wir noch sagen möchte...')),
            ],
        ),
    ]
