# Generated by Django 3.2.12 on 2022-03-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorfreude', '0003_auto_20220309_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gilde',
        ),
        migrations.AlterField(
            model_name='post',
            name='bundesgruppe',
            field=models.CharField(max_length=256, verbose_name='Bundesgliederung'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fahrtenname',
            field=models.CharField(max_length=128, verbose_name='Name von Dir oder Deiner Gruppe'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gedanken',
            field=models.TextField(verbose_name='Wenn ich (wir) an das Bundeslager 2022 denke(n), dann...'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sagen',
            field=models.TextField(verbose_name='Und was ich (wir) noch gerne sagen möchte(n)...'),
        ),
    ]
