# Generated by Django 3.2.5 on 2021-11-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20150618_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='is archived?'),
        ),
    ]
