# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0021_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='house',
            name='capacity_house',
        ),
        migrations.RemoveField(
            model_name='house',
            name='capacity_outdoor',
        ),
        migrations.AddField(
            model_name='house',
            name='accessibility_baker',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Entfernung zum nächsten Bäcker'),
        ),
        migrations.AddField(
            model_name='house',
            name='accessibility_bus',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Entfernung zum nächsten Bus'),
        ),
        migrations.AddField(
            model_name='house',
            name='accessibility_other',
            field=models.TextField(blank=True, max_length=4096, verbose_name='Sonstiges in der Nähe'),
        ),
        migrations.AddField(
            model_name='house',
            name='accessibility_parking',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Anzahl der Parkplätze'),
        ),
        migrations.AddField(
            model_name='house',
            name='accessibility_shop',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Entfernung zur Einkaufsmöglichkeit'),
        ),
        migrations.AddField(
            model_name='house',
            name='accessibility_train',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Entfernung zum nächsten Bahnhof'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_dishes',
            field=models.BooleanField(default=False, verbose_name='Geschirr und Besteck'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_dishwasher',
            field=models.BooleanField(default=False, verbose_name='Geschirrspüler'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_fridge',
            field=models.BooleanField(default=False, verbose_name='Kühlschrank'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_hot_water',
            field=models.BooleanField(default=False, verbose_name='Heißes Wasser'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_other',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Sonstige Küchengeräte'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_oven',
            field=models.BooleanField(default=False, verbose_name='Backofen'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_pots',
            field=models.BooleanField(default=False, verbose_name='Große Töpfe'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_sink',
            field=models.BooleanField(default=False, verbose_name='Spüle'),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen_stove',
            field=models.BooleanField(default=False, verbose_name='Herd'),
        ),
        migrations.AddField(
            model_name='house',
            name='location_countryy',
            field=models.BooleanField(default=False, verbose_name='ländlich'),
        ),
        migrations.AddField(
            model_name='house',
            name='location_special',
            field=models.TextField(blank=True, max_length=4096, verbose_name='Besonderheiten'),
        ),
        migrations.AddField(
            model_name='house',
            name='location_urban',
            field=models.BooleanField(default=False, verbose_name='städtisch'),
        ),
        migrations.AddField(
            model_name='house',
            name='room_chairs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl der Stühle'),
        ),
        migrations.AddField(
            model_name='house',
            name='room_size',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Größe'),
        ),
        migrations.AddField(
            model_name='house',
            name='room_tables',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl der Tische'),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms_chairs',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Anzahl der Stühle in weiteren Räumen'),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms_tables',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Anzahl der Tische in weiteren Räumen'),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms_total',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Anzahl weiterer Räume'),
        ),
        migrations.AddField(
            model_name='house',
            name='sleep_beds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl der Betten'),
        ),
        migrations.AddField(
            model_name='house',
            name='sleep_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fußboden'),
        ),
        migrations.AddField(
            model_name='house',
            name='sleep_mattresses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl der Matrazen'),
        ),
        migrations.AddField(
            model_name='house',
            name='toilets_separate',
            field=models.BooleanField(default=False, verbose_name='geschlechtergetrennt'),
        ),
        migrations.AddField(
            model_name='house',
            name='toilets_shower',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl der Duschen'),
        ),
        migrations.AddField(
            model_name='house',
            name='toilets_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl der Toiletten'),
        ),
        migrations.AddField(
            model_name='house',
            name='toilets_washbasin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl der Waschbecken'),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=4096, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact_name',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Kontaktdaten der Vermietung'),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Sonstige Beschreibung'),
        ),
        migrations.AlterField(
            model_name='house',
            name='display_name',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Berechneter Standort'),
        ),
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.FloatField(blank=True, max_length=4096, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.FloatField(blank=True, max_length=4096, null=True, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=4096, verbose_name='Name des Heimes/Hauses'),
        ),
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Bundesgruppe des Heimes'),
        ),
        migrations.AlterField(
            model_name='house',
            name='plz',
            field=models.CharField(blank=True, max_length=4096, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_extern',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Preise für Externe'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_intern',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Preise für Pfadfinder'),
        ),
        migrations.AlterField(
            model_name='house',
            name='situation',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Lage'),
        ),
        migrations.AlterField(
            model_name='house',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intern.State', verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='house',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Link zum Heim/Haus'),
        ),
    ]
