# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0023_auto_20160306_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='location_countryy',
            new_name='location_country',
        ),
    ]
