# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0027_house_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price_other',
            field=models.TextField(blank=True, max_length=4096, verbose_name='Sonstige Kosten'),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact_name',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Ansprechpartner für die Vermietung'),
        ),
    ]
