# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0029_house_rooms_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='room_chairs',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Anzahl der Stühle'),
        ),
        migrations.AlterField(
            model_name='house',
            name='room_tables',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Anzahl der Tische'),
        ),
    ]
