# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0030_auto_20160311_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Öffentlich?'),
        ),
    ]
