# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0031_house_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Dein Name'),
        ),
        migrations.AddField(
            model_name='house',
            name='user_mail',
            field=models.EmailField(blank=True, max_length=1024, verbose_name='Deine E-Mail Adresse'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
    ]
