# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0032_auto_20160313_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='termine/', verbose_name='Anhang'),
        ),
    ]
