# Generated by Django 2.2.1 on 2019-05-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('intern', '0036_auto_20180504_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='kitchen_dishes',
            field=models.BooleanField(blank=True, default=False, verbose_name='Geschirr und Besteck'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_dishwasher',
            field=models.BooleanField(blank=True, default=False, verbose_name='Geschirrspüler'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_fridge',
            field=models.BooleanField(blank=True, default=False, verbose_name='Kühlschrank'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_hot_water',
            field=models.BooleanField(blank=True, default=False, verbose_name='Heißes Wasser'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_oven',
            field=models.BooleanField(blank=True, default=False, verbose_name='Backofen'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_pots',
            field=models.BooleanField(blank=True, default=False, verbose_name='Große Töpfe'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_sink',
            field=models.BooleanField(blank=True, default=False, verbose_name='Spüle'),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_stove',
            field=models.BooleanField(blank=True, default=False, verbose_name='Herd'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location_country',
            field=models.BooleanField(blank=True, default=False, verbose_name='ländlich'),
        ),
        migrations.AlterField(
            model_name='house',
            name='location_urban',
            field=models.BooleanField(blank=True, default=False, verbose_name='städtisch'),
        ),
        migrations.AlterField(
            model_name='house',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='intern.State', verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='house',
            name='toilets_separate',
            field=models.BooleanField(blank=True, default=False, verbose_name='geschlechtergetrennt'),
        ),
    ]
