# Generated by Django 3.2.15 on 2022-10-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0038_auto_20190525_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
