# Generated by Django 6.1.1 on 2026-09-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0039_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price_intern',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Preise für Pfadfinderinnen und Pfadfinder'),
        ),
    ]
