# Generated by Django 2.2.1 on 2019-05-25 19:40

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20150802_0017'), ('blog', '0003_auto_20150802_0043'),
                ('blog', '0004_auto_20150802_0045'), ('blog', '0005_auto_20150802_0050'),
                ('blog', '0006_auto_20150802_0056'), ('blog', '0007_post_author'), ('blog', '0008_auto_20150802_1432'),
                ('blog', '0009_category_intro'), ('blog', '0010_auto_20180604_2248')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung')),
            ],
            options={
                'verbose_name_plural': 'Kategorien',
                'verbose_name': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('archive', models.BooleanField(default=False, verbose_name='Archiviert?')),
                ('public', models.BooleanField(default=True, verbose_name='Öffentlich?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('category',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category',
                                   verbose_name='Kategorie')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('file', models.FileField(blank=True, null=True, upload_to='blogpost', verbose_name='Anhang')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'Beiträge',
                'verbose_name': 'Beitrag',
            },
        ),
    ]
