# Generated by Django 2.2.1 on 2019-05-25 19:43

import datetime

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel *')),
                ('target', models.CharField(max_length=128, verbose_name='Wie alt sind meine Mädchen / Jungen? *')),
                (
                    'preparation',
                    models.TextField(blank=True, max_length=4096, verbose_name='Was habe ich vorbereitet?')),
                ('execution', models.TextField(max_length=4096, verbose_name='Was haben wir gemacht? *')),
                ('greatness', models.TextField(blank=True, max_length=4096, verbose_name='Was war daran so toll?')),
                ('contact_name', models.CharField(blank=True, max_length=128, verbose_name='Mein Name')),
                ('contact_group', models.CharField(blank=True, max_length=128, verbose_name='Meine Gruppe')),
                ('contact_mail', models.EmailField(blank=True, max_length=254, verbose_name='Meine E-Mail')),
                ('file1', models.FileField(blank=True, null=True, upload_to='heimabende', verbose_name='1. Anhang')),
                ('file2', models.FileField(blank=True, null=True, upload_to='heimabende', verbose_name='2. Anhang')),
                ('file3', models.FileField(blank=True, null=True, upload_to='heimabende', verbose_name='3. Anhang')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Erstellt am')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Heimabendprogramm',
                'verbose_name_plural': 'Heimabendprogramme',
                'ordering': ('created',),
            },
        ),
    ]
