# Generated by Django 5.1.1 on 2024-09-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evening_program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
    ]
