# Generated by Django 2.2.1 on 2019-05-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('archive', '0002_auto_20180706_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Item',
                                    verbose_name='Bezieht sich auf'),
        ),
    ]
