# Generated by Django 3.2.23 on 2024-01-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_item_doctype_old_to_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='doctype',
            field=models.CharField(blank=True, choices=[('Adressverzeichnis', 'Adressverzeichnis'), ('Chronik / Dokumentation', 'Chronik / Dokumentation'), ('Fahrtenbericht', 'Fahrtenbericht'), ('Kalender', 'Kalender'), ('Lagerheft', 'Lagerheft'), ('Lebensbericht', 'Lebensbericht'), ('Liederbuch', 'Liederbuch'), ('Ordnung', 'Ordnung'), ('Protokoll', 'Protokoll'), ('Reden', 'Reden'), ('Schöpferisches (Gedicht, Lieder, ...)', 'Schöpferisches (Gedicht, Lieder, ...)'), ('Schriftwechsel', 'Schriftwechsel'), ('Sonstiges', 'Sonstiges'), ('Zeitschrift', 'Zeitschrift'), ('Zeitungsartikel', 'Zeitungsartikel')], max_length=256, null=True, verbose_name='Dokumenttyp'),
        ),
    ]
