# Generated by Django 5.0.6 on 2024-05-10 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_alter_item_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.doctype', verbose_name='Dokument Typ'),
        ),
    ]
