# Generated by Django 5.2.7 on 2025-10-23 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_add_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Monat'),
        ),
    ]
