# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='city',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='link',
            name='state',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Bundesland'),
        ),
    ]
