# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20160221_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Öffentlich?'),
        ),
    ]
